name: Generate Chart Readme

on:
  pull_request:
    branches:
      - master
    paths:
      - 'bitnami/airflow/values.yaml'
      - 'bitnami/common/values.yaml'
      - 'bitnami/concourse/values.yaml'      
      - 'bitnami/dokuwiki/values.yaml'
      - 'bitnami/drupal/values.yaml'
      - 'bitnami/ejbca/values.yaml'
      - 'bitnami/harbor/values.yaml'
      - 'bitnami/influxdb/values.yaml'
      - 'bitnami/jasperreports/values.yaml'
      - 'bitnami/fluentd/values.yaml'
      - 'bitnami/grafana/values.yaml'
      - 'bitnami/grafana-operator/values.yaml'
      - 'bitnami/joomla/values.yaml'
      - 'bitnami/jupyterhub/values.yaml'
      - 'bitnami/kafka/values.yaml'
      - 'bitnami/keycloak/values.yaml'
      - 'bitnami/kiam/values.yaml'
      - 'bitnami/kibana/values.yaml'
      - 'bitnami/kong/values.yaml'
      - 'bitnami/kube-prometheus/values.yaml'
      - 'bitnami/kube-state-metrics/values.yaml'
      - 'bitnami/kubernetes-event-exporter/values.yaml'
      - 'bitnami/kubewatch/values.yaml'
      - 'bitnami/logstash/values.yaml'
      - 'bitnami/magento/values.yaml'
      - 'bitnami/mariadb/values.yaml'
      - 'bitnami/mariadb-galera/values.yaml'
      - 'bitnami/metrics-server/values.yaml'
      - 'bitnami/minio/values.yaml'
      - 'bitnami/mongodb/values.yaml'
      - 'bitnami/mongodb-sharded/values.yaml'
      - 'bitnami/moodle/values.yaml'
      - 'bitnami/mxnet/values.yaml'
      - 'bitnami/mysql/values.yaml'
      - 'bitnami/nats/values.yaml'
      - 'bitnami/nginx/values.yaml'
      - 'bitnami/nginx-ingress-controller/values.yaml'
      - 'bitnami/node/values.yaml'
      - 'bitnami/node-exporter/values.yaml'
      - 'bitnami/oauth2-proxy/values.yaml'
      - 'bitnami/opencart/values.yaml'
      - 'bitnami/orangehrm/values.yaml'
      - 'bitnami/owncloud/values.yaml'
      - 'bitnami/parse/values.yaml'
      - 'bitnami/phabricator/values.yaml'
      - 'bitnami/phpbb/values.yaml'
      - 'bitnami/phpmyadmin/values.yaml'
      - 'bitnami/postgresql/values.yaml'
      - 'bitnami/postgresql-ha/values.yaml'
      - 'bitnami/prestashop/values.yaml'
      - 'bitnami/pytorch/values.yaml'
      - 'bitnami/rabbitmq/values.yaml'
      - 'bitnami/redis/values.yaml'
      - 'bitnami/redis-cluster/values.yaml'
      - 'bitnami/redmine/values.yaml'
      - 'bitnami/solr/values.yaml'
      - 'bitnami/spark/values.yaml'
      - 'bitnami/spring-cloud-dataflow/values.yaml'
      - 'bitnami/suitecrm/values.yaml'
      - 'bitnami/tomcat/values.yaml'
      - 'bitnami/wavefront/values.yaml'
      - 'bitnami/wavefront-adapter-for-istio/values.yaml'
      - 'bitnami/wavefront-hpa-adapter/values.yaml'
      - 'bitnami/wavefront-prometheus-storage-adapter/values.yaml'
      - 'bitnami/wildfly/values.yaml'
      - 'bitnami/wordpress/values.yaml'
      - 'bitnami/zookeeper/values.yaml'

jobs:
  generate-chart-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout bitnami-labs/readme-generator-for-helm
        uses: actions/checkout@v2
        with:
          repository: "bitnami-labs/readme-generator-for-helm"
          path: readme-generator-for-helm

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('readme-generator-for-helm/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install readme-generator-for-helm dependencies
        run: cd readme-generator-for-helm && npm install

      - name: Checkout bitnami/charts
        uses: actions/checkout@v2
        with:
          path: charts

      - name: Get list of files with changes in Pull Request
        id: pr-file-changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          fileOutput: " "

      - name: Prepare readme-generator-for-helm inputs
        run: |
          cat $HOME/files.txt | tr " " "\n" | grep values\\.yaml > raw-inputs
          cat raw-inputs | sed 's/values.yaml/README.md/' >> raw-inputs
          cat raw-inputs | sed 's/bitnami/charts\/bitnami/' > prepared-inputs

      - name: Execute readme-generator-for-helm
        run: readme-generator-for-helm/bin/index.js -r $(cat prepared-inputs | grep README) -v $(cat prepared-inputs | grep values)

      - name: Output generated README.md
        run: cat $(cat prepared-inputs | grep README)
